---
title: f10w3r dance
baseurl: "https://blog.f10w3r.dance"
desc: Learning never exhausts the mind. - [Leonardo da Vinci]
about: "Enki. Security Analysis Researcher\t
Best Of The Best 7th vulnerability\t
Kookmin Univ. Infomation Security Crypto Mathematical\t"

image: https://github.com/f10w3r-dance/f10w3r-dance.github.io/blob/main/png/klipartz.com.png?raw=true
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
