---
title: f10w3r dance
baseurl: "https://blog.f10w3r.dance"
desc: Security Researcher
about: Hello world :)
image: https://www.google.com/url?sa=i&url=https%3A%2F%2Fpnghut.com%2Fpng%2FbCt8q2CUhQ%2Flinux-kernel-tux-logo-distribution-transparent-png&psig=AOvVaw3oZblaBVOK9vo389SEcobL&ust=1608481681651000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCNCfp6672u0CFQAAAAAdAAAAABAJ
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
